name: C++ Build & Sanity Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: Build Project
        run: make

      - name: Run Simulator
        run: ./minios
